name: Actualizar clima

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

  permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Obtener clima
        run: |
          curl -s "https://clima.kevin-diaz98.workers.dev/" > clima.json

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add clima.json
          git diff --cached --quiet || git commit -m "clima actualizado"
          git push
